import type { ServiceConfig } from './types';

export enum ServicePath {
  AUTH = 'auth',
  BETTER_AUTH = 'better-auth',
  USERS = 'users',
  PRODUCTS = 'products',
  ORGANIZATIONS = 'organizations',
  ANALYTICS = 'analytics',
  NOTIFICATIONS = 'notifications',
  PATTERNS = 'patterns',
  INTERACTIONS = 'interactions',
  CHAT = 'chat',
  QNA = 'qna',
  MCP = 'mcp',
  BILLING = 'billing',
  CRAWLER_JOBS = 'crawler-jobs',
  CCTV = 'cctv',
  INGEST = 'ingest',
}

export enum ServiceName {
  AUTH = 'core-auth-service',
  USERS = 'core-user-service',
  PRODUCTS = 'core-product-service',
  ORGANIZATIONS = 'core-organization-service',
  ANALYTICS = 'core-analytics-service',
  NOTIFICATIONS = 'core-notification-service',
  PATTERNS = 'core-pattern-service',
  INTERACTIONS = 'core-interaction-service',
  CHAT = 'bff-chat-service',
  QNA = 'bff-qna-service',
  MCP = 'mcp-service',
  BILLING = 'core-billing-service',
  CCTV = 'cctv-ingest-service',
  WEB_INGEST = 'web-ingest-service',
}

export const PROD_ORIGINS = [
  'https://crowai.dev',
  'https://auth.crowai.dev',
  'https://app.crowai.dev',
  'https://api.crowai.dev',
  'https://dev.crowai.dev',
  'https://dev.auth.crowai.dev',
  'https://dev.app.crowai.dev',
  'https://dev.api.crowai.dev',
  'https://internal.auth-api.crowai.dev',
  'https://internal.users.crowai.dev',
  'https://internal.products.crowai.dev',
  'https://internal.orgs.crowai.dev',
  'https://internal.analytics.crowai.dev',
  'https://internal.notifications.crowai.dev',
  'https://internal.patterns.crowai.dev',
  'https://internal.interactions.crowai.dev',
  'https://internal.chat.crowai.dev',
  'https://internal.qna.crowai.dev',
  'https://internal.mcp.crowai.dev',
  'https://internal.billing.crowai.dev',
  'https://dev.internal.auth-api.crowai.dev',
  'https://dev.internal.users.crowai.dev',
  'https://dev.internal.products.crowai.dev',
  'https://dev.internal.orgs.crowai.dev',
  'https://dev.internal.analytics.crowai.dev',
  'https://dev.internal.notifications.crowai.dev',
  'https://dev.internal.patterns.crowai.dev',
  'https://dev.internal.interactions.crowai.dev',
  'https://dev.interactions.crowai.dev',
  'https://dev.internal.chat.crowai.dev',
  'https://dev.internal.qna.crowai.dev',
  'https://dev.mcp.crowai.dev',
  'https://dev.internal.billing.crowai.dev',
  'https://dev.cctv.crowai.dev',
  'https://cctv.crowai.dev',
  'https://dashboard.crowai.dev',
  'https://dev.dashboard.crowai.dev',
  'https://rogue.crowai.dev',
  'https://dev.rogue.crowai.dev',
];

export const LOCAL_ORIGINS = [
  'http://localhost:3000',
  'http://localhost:3001',
  'http://localhost:3002',
  'http://localhost:8000',
  'http://localhost:8001',
  'http://localhost:8002',
  'http://localhost:8003',
  'http://localhost:8004',
  'http://localhost:8005',
  'http://localhost:8006',
  'http://localhost:8007',
  'http://localhost:8008',
  'http://localhost:8009',
  'http://localhost:8010',
  'http://localhost:8011',
  'http://localhost:8012',
];

export const SERVICES: ServiceConfig[] = [
  {
    name: ServiceName.AUTH,
    path: ServicePath.AUTH,
    urls: {
      local: 'http://localhost:8001',
      dev: 'https://dev.internal.auth-api.crowai.dev',
      prod: 'https://internal.auth-api.crowai.dev',
    },
  },
  {
    name: ServiceName.AUTH,
    path: ServicePath.BETTER_AUTH,
    urls: {
      local: 'http://localhost:8001',
      dev: 'https://dev.internal.auth-api.crowai.dev',
      prod: 'https://internal.auth-api.crowai.dev',
    },
  },
  {
    name: ServiceName.USERS,
    path: ServicePath.USERS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8002',
      dev: 'https://dev.internal.users.crowai.dev',
      prod: 'https://internal.users.crowai.dev',
    },
  },
  {
    name: ServiceName.PRODUCTS,
    path: ServicePath.PRODUCTS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8003',
      dev: 'https://dev.internal.products.crowai.dev',
      prod: 'https://internal.products.crowai.dev',
    },
  },
  {
    name: ServiceName.ORGANIZATIONS,
    path: ServicePath.ORGANIZATIONS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8004',
      dev: 'https://dev.internal.orgs.crowai.dev',
      prod: 'https://internal.orgs.crowai.dev',
    },
  },
  {
    name: ServiceName.ANALYTICS,
    path: ServicePath.ANALYTICS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8005',
      dev: 'https://dev.internal.analytics.crowai.dev',
      prod: 'https://internal.analytics.crowai.dev',
    },
  },
  {
    name: ServiceName.NOTIFICATIONS,
    path: ServicePath.NOTIFICATIONS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8006',
      dev: 'https://dev.internal.notifications.crowai.dev',
      prod: 'https://internal.notifications.crowai.dev',
    },
  },
  {
    name: ServiceName.PATTERNS,
    path: ServicePath.PATTERNS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8007',
      dev: 'https://dev.internal.patterns.crowai.dev',
      prod: 'https://internal.patterns.crowai.dev',
    },
  },
  {
    name: ServiceName.INTERACTIONS,
    path: ServicePath.INTERACTIONS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8008',
      dev: 'https://dev.interactions.crowai.dev',
      prod: 'https://interactions.crowai.dev',
    },
  },
  {
    name: ServiceName.CHAT,
    path: ServicePath.CHAT,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8009',
      dev: 'https://dev.internal.chat.crowai.dev',
      prod: 'https://internal.chat.crowai.dev',
    },
  },
  {
    name: ServiceName.QNA,
    path: ServicePath.QNA,
    requiresAuth: false,
    urls: {
      local: 'http://localhost:8010',
      dev: 'https://dev.internal.qna.crowai.dev',
      prod: 'https://internal.qna.crowai.dev',
    },
  },
  {
    name: ServiceName.MCP,
    path: ServicePath.MCP,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8011',
      dev: 'https://dev.mcp.crowai.dev',
      prod: 'https://internal.mcp.crowai.dev',
    },
  },
  {
    name: ServiceName.BILLING,
    path: ServicePath.BILLING,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8012',
      dev: 'https://dev.internal.billing.crowai.dev',
      prod: 'https://internal.billing.crowai.dev',
    },
  },
  {
    name: ServiceName.PRODUCTS,
    path: ServicePath.CRAWLER_JOBS,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8003',
      dev: 'https://dev.internal.products.crowai.dev',
      prod: 'https://internal.products.crowai.dev',
    },
  },
  {
    name: ServiceName.CCTV,
    path: ServicePath.CCTV,
    urls: {
      local: 'http://localhost:8015',
      dev: 'https://dev.cctv.crowai.dev',
      prod: 'https://cctv.crowai.dev',
    },
  },
  {
    name: ServiceName.WEB_INGEST,
    path: ServicePath.INGEST,
    requiresAuth: true,
    urls: {
      local: 'http://localhost:8013',
      dev: 'https://dev.internal.ingest-worker.crowai.dev',
      prod: 'https://internal.ingest-worker.crowai.dev',
    },
  },
];
